[versions]
ktx = "1.9.0"
runtimektx = "2.5.1"
activitycompose = "1.6.1"
composeui = "1.3.3"
uitooling = "1.3.3"
runtime-live-data-compose = "1.3.3"
material3 = "1.0.1"
datastore-preferences = "1.0.0"
datastore = "1.0.0"
hilt = "2.44.2"
hilt-compiler = "2.44.2"
protobuf = "3.21.12"
kotlin-serialization = "1.5.0-RC"
retrofit-converter = "0.8.0"
okhttp = "4.10.0"
retrofit2 = "2.9.0"

junit = "4.13.2"
androidx-junit = "1.1.5"
espresso = "3.5.1"
compose-uitest = "1.3.3"
compose-uitooling = "1.3.3"
compose-uitestmanifest = "1.3.3"



[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "runtimektx" }
androidx-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activitycompose" }
androidx-compose = { group = "androidx.compose.ui", name = "ui", version.ref = "composeui" }
androidx-composeuitooling = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uitooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
runtime-live-data-compose= { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtime-live-data-compose" }
androidx-datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-compiler" }
protobuf = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
retrofit-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-converter" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
compose-uitest = { group = "ndroidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-uitest" }
compose-uitooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-uitooling" }
compose-uitestmanifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-uitestmanifest" }



[plugins]